version: "3"
services:
    api: #container
        image: bmate12/fastapi
        depends_on:
            - postgres
        ports:
            - 8000:8000 #local:cont
        # command: uvicorn app.main:app --host 0.0.0.0 --port 8000
        # env_file:
        #     - ./.env
        environment:
            - database_hostname=${database_hostname}
            - database_port=${database_port}
            - database_name=${database_name}
            - database_password=${database_password}
            - database_username=${database_username}
            - secret_key=${secret_key}
            - algorithm=${algorithm}
            - access_token_expire_minutes=${access_token_expire_minutes}
    postgres:
        image: postgres
        environment:
            - POSTGRES_PASSWORD=${database_password}
            - POSTGRES_DB=${database_name}
        volumes:
            - postgres-db:/var/lib/postgresql/data

volumes:
    postgres-db: