name: Build and Deploy Code

on: [push, pull_request]

jobs:
  job1:
    env:
      database_hostname: ${{secrets.database_hostname}}
      database_port: ${{secrets.database_port}}
      database_name: ${{secrets.database_name}}
      database_password: ${{secrets.database_password}}
      database_username: ${{secrets.database_username}}
      secret_key: ${{secrets.secret_key}}
      algorithm: ${{secrets.algorithm}}
      access_token_expire_minutes: ${{secrets.access_token_expire_minutes}}
    runs-on: ubuntu-20.04
    steps:
      - name: pulling git repo
        uses: actions/checkout@v2
      - name: Install python ver 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: update pip
        run: python -m pip install --upgrade pip
      - name: install all dependencies
        run: pip install -r requirements.txt 
      - name: test with pytest
        run: |
          pip install pytest
          pytest