name: Build and Deploy Code

on: [push, pull_request]

jobs:
  job1:
    environment:
      name: testing
    env:
      database_hostname: ${{secrets.DATABASE_HOSTNAME}}
      database_port: ${{secrets.DATABASE_PORT}}
      database_name: ${{secrets.DATABASE_NAME}}
      database_password: ${{secrets.DATABASE_PASSWORD}}
      database_username: ${{secrets.DATABASE_USERNAME}}
      secret_key: ${{secrets.SECRET_KEY}}
      algorithm: ${{secrets.ALGORITHM}}
      access_token_expire_minutes: ${{secrets.ACCESS_TOKEN_EXPIRE_MINUTES}}

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: ${{secrets.DATABASE_PASSWORD}}
          POSTGRES_DB: ${{secrets.DATABASE_NAME}}_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    runs-on: ubuntu-20.04
    steps:
      - name: pulling git repo
        uses: actions/checkout@v2
      - name: Install python ver 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: update pip
        run: python -m pip install --upgrade pip
      - name: install all dependencies
        run: pip install -r requirements.txt 
      - name: test with pytest
        run: |
          pip install pytest
          pytest